# Convert character to binary 

In [90]:
#%pylab inline
import numpy as np

In [70]:
data = array(['m','f','m','m'])
for a in data :
    print (a)

m
f
m
m


In [71]:
array([1,2,3,4]) == 1

array([ True, False, False, False], dtype=bool)

In [72]:
def convert(data):
    lst = []
    binary = data == 'm'
    for x in binary:
        no = int(x)
        lst.append(no)
    return lst    

In [73]:
convert(data)

[1, 0, 1, 1]

## Normalization 

In [108]:
d = np.array([1, 10, 0.5, 43, 0.12, 8])
d.max()

43.0

In [111]:
def Nor(data,f_max=1,f_min=-1):
    maxNo,minNo = data.max(),data.min()
    factor = (f_max - f_min) / (maxNo - minNo)
    normar = f_min+data*factor
    return normar

In [112]:
Nor(data)

array([-0.95335821, -0.53358209, -0.9766791 ,  1.00559701, -0.99440299,
       -0.62686567])